services:
  - type: web
    name: backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: SOME_ENV_VAR
        value: "some-value"
    # Optionally, you can specify the region and plan
    # plan: free
    # region: oregon
